FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

# Expose Flask app port
EXPOSE 8080

# Start Flask app when the container runs
CMD ["python", "app.py"]




